# This rule is not used by the project registry-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to registry.k8s.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterregistrycredential-viewer-role
rules:
- apiGroups:
  - registry.k8s.io
  resources:
  - clusterregistrycredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.k8s.io
  resources:
  - clusterregistrycredentials/status
  verbs:
  - get
